from sqlalchemy import Column, String, Date, Time, DateTime, Boolean, Numeric, ForeignKey, PrimaryKeyConstraint, BigInteger
from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID
from .base import Base

class BillingDocumentHeader(Base):
    __tablename__ = "billing_document_headers"
    billing_document = Column(String(255), primary_key=True)
    billing_document_type = Column(String(255))
    creation_date = Column(Date)
    creation_time = Column(Time)
    last_change_datetime = Column(TIMESTAMP(timezone=True))
    billing_document_date = Column(Date)
    billing_document_is_cancelled = Column(Boolean, default=False)
    cancelled_billing_document = Column(String(255))
    total_net_amount = Column(Numeric(18, 4))
    transaction_currency = Column(String(255))
    company_code = Column(String(255))
    fiscal_year = Column(String(255))
    accounting_document = Column(String(255))
    sold_to_party = Column(String(255))

class BillingDocumentCancellation(Base):
    __tablename__ = "billing_document_cancellations"
    billing_document = Column(String(255), primary_key=True)
    billing_document_type = Column(String(255))
    creation_date = Column(Date)
    creation_time = Column(Time)
    last_change_datetime = Column(TIMESTAMP(timezone=True))
    billing_document_date = Column(Date)
    billing_document_is_cancelled = Column(Boolean, default=False)
    cancelled_billing_document = Column(String(255))
    total_net_amount = Column(Numeric(18, 4))
    transaction_currency = Column(String(255))
    company_code = Column(String(255))
    fiscal_year = Column(String(255))
    accounting_document = Column(String(255))
    sold_to_party = Column(String(255))

class BillingDocumentItem(Base):
    __tablename__ = "billing_document_items"
    billing_document = Column(String(255), primary_key=True)
    billing_document_item = Column(String(255), primary_key=True)
    material = Column(String(255))
    billing_quantity = Column(Numeric(18, 2))
    billing_quantity_unit = Column(String(255))
    net_amount = Column(Numeric(18, 4))
    transaction_currency = Column(String(255))
    reference_sd_document = Column(String(255))
    reference_sd_document_item = Column(String(255))

class BusinessPartnerAddress(Base):
    __tablename__ = "business_partner_addresses"
    business_partner = Column(String(255), primary_key=True)
    address_id = Column(String(255), primary_key=True)
    validity_start_date = Column(Date)
    validity_end_date = Column(Date)
    address_uuid = Column(String(255))
    address_time_zone = Column(String(255))
    city_name = Column(String(255))
    country = Column(String(255))
    po_box = Column(String(255))
    po_box_deviating_city_name = Column(String(255))
    po_box_deviating_country = Column(String(255))
    po_box_deviating_region = Column(String(255))
    po_box_is_without_number = Column(Boolean, default=False)
    po_box_lobby_name = Column(String(255))
    po_box_postal_code = Column(String(255))
    postal_code = Column(String(255))
    region = Column(String(255))
    street_name = Column(String(255))
    tax_jurisdiction = Column(String(255))
    transport_zone = Column(String(255))

class BusinessPartner(Base):
    __tablename__ = "business_partners"
    business_partner = Column(String(255), primary_key=True)
    customer = Column(String(255))
    business_partner_category = Column(String(255))
    business_partner_full_name = Column(String(255))
    business_partner_grouping = Column(String(255))
    business_partner_name = Column(String(255))
    correspondence_language = Column(String(255))
    created_by_user = Column(String(255))
    creation_date = Column(Date)
    creation_time = Column(Time)
    first_name = Column(String(255))
    form_of_address = Column(String(255))
    industry = Column(String(255))
    last_change_date = Column(Date)
    last_name = Column(String(255))
    organization_bp_name1 = Column(String(255))
    organization_bp_name2 = Column(String(255))
    business_partner_is_blocked = Column(Boolean, default=False)
    is_marked_for_archiving = Column(Boolean, default=False)

class CustomerCompanyAssignment(Base):
    __tablename__ = "customer_company_assignments"
    customer = Column(String(255), primary_key=True)
    company_code = Column(String(255), primary_key=True)
    accounting_clerk = Column(String(255))
    accounting_clerk_fax_number = Column(String(255))
    accounting_clerk_internet_address = Column(String(255))
    accounting_clerk_phone_number = Column(String(255))
    alternative_payer_account = Column(String(255))
    payment_blocking_reason = Column(String(255))
    payment_methods_list = Column(String(255))
    payment_terms = Column(String(255))
    reconciliation_account = Column(String(255))
    deletion_indicator = Column(Boolean, default=False)
    customer_account_group = Column(String(255))

class CustomerSalesAreaAssignment(Base):
    __tablename__ = "customer_sales_area_assignments"
    customer = Column(String(255), primary_key=True)
    sales_organization = Column(String(255), primary_key=True)
    distribution_channel = Column(String(255), primary_key=True)
    division = Column(String(255), primary_key=True)
    billing_is_blocked_for_customer = Column(String(255))
    complete_delivery_is_defined = Column(Boolean, default=False)
    credit_control_area = Column(String(255))
    currency = Column(String(255))
    customer_payment_terms = Column(String(255))
    delivery_priority = Column(String(255))
    incoterms_classification = Column(String(255))
    incoterms_location1 = Column(String(255))
    sales_group = Column(String(255))
    sales_office = Column(String(255))
    shipping_condition = Column(String(255))
    sls_unlmtd_ovrdeliv_is_allwd = Column(Boolean, default=False)
    supplying_plant = Column(String(255))
    sales_district = Column(String(255))
    exchange_rate_type = Column(String(255))

class JournalEntryItemAccountsReceivable(Base):
    __tablename__ = "journal_entry_items_accounts_receivable"
    company_code = Column(String(255), primary_key=True)
    fiscal_year = Column(String(255), primary_key=True)
    accounting_document = Column(String(255), primary_key=True)
    accounting_document_item = Column(String(255), primary_key=True)
    gl_account = Column(String(255))
    reference_document = Column(String(255))
    cost_center = Column(String(255))
    profit_center = Column(String(255))
    transaction_currency = Column(String(255))
    amount_in_transaction_currency = Column(Numeric(18, 4))
    company_code_currency = Column(String(255))
    amount_in_company_code_currency = Column(Numeric(18, 4))
    posting_date = Column(Date)
    document_date = Column(Date)
    accounting_document_type = Column(String(255))
    assignment_reference = Column(String(255))
    last_change_datetime = Column(TIMESTAMP(timezone=True))
    customer = Column(String(255))
    financial_account_type = Column(String(255))
    clearing_date = Column(Date)
    clearing_accounting_document = Column(String(255))
    clearing_doc_fiscal_year = Column(String(255))

class OutboundDeliveryHeader(Base):
    __tablename__ = "outbound_delivery_headers"
    delivery_document = Column(String(255), primary_key=True)
    actual_goods_movement_date = Column(Date)
    actual_goods_movement_time = Column(Time)
    creation_date = Column(Date)
    creation_time = Column(Time)
    delivery_block_reason = Column(String(255))
    hdr_general_incompletion_status = Column(String(255))
    header_billing_block_reason = Column(String(255))
    last_change_date = Column(Date)
    overall_goods_movement_status = Column(String(255))
    overall_picking_status = Column(String(255))
    overall_proof_of_delivery_status = Column(String(255))
    shipping_point = Column(String(255))

class OutboundDeliveryItem(Base):
    __tablename__ = "outbound_delivery_items"
    delivery_document = Column(String(255), primary_key=True)
    delivery_document_item = Column(String(255), primary_key=True)
    actual_delivery_quantity = Column(Numeric(18, 2))
    batch = Column(String(255))
    delivery_quantity_unit = Column(String(255))
    item_billing_block_reason = Column(String(255))
    last_change_date = Column(Date)
    plant = Column(String(255))
    reference_sd_document = Column(String(255))
    reference_sd_document_item = Column(String(255))
    storage_location = Column(String(255))

class PaymentAccountsReceivable(Base):
    __tablename__ = "payments_accounts_receivable"
    company_code = Column(String(255), primary_key=True)
    fiscal_year = Column(String(255), primary_key=True)
    accounting_document = Column(String(255), primary_key=True)
    accounting_document_item = Column(String(255), primary_key=True)
    clearing_date = Column(Date)
    clearing_accounting_document = Column(String(255))
    clearing_doc_fiscal_year = Column(String(255))
    amount_in_transaction_currency = Column(Numeric(18, 4))
    transaction_currency = Column(String(255))
    amount_in_company_code_currency = Column(Numeric(18, 4))
    company_code_currency = Column(String(255))
    customer = Column(String(255))
    invoice_reference = Column(String(255))
    invoice_reference_fiscal_year = Column(String(255))
    sales_document = Column(String(255))
    sales_document_item = Column(String(255))
    posting_date = Column(Date)
    document_date = Column(Date)
    assignment_reference = Column(String(255))
    gl_account = Column(String(255))
    financial_account_type = Column(String(255))
    profit_center = Column(String(255))
    cost_center = Column(String(255))

class Plant(Base):
    __tablename__ = "plants"
    plant = Column(String(255), primary_key=True)
    plant_name = Column(String(255))
    valuation_area = Column(String(255))
    plant_customer = Column(String(255))
    plant_supplier = Column(String(255))
    factory_calendar = Column(String(255))
    default_purchasing_organization = Column(String(255))
    sales_organization = Column(String(255))
    address_id = Column(String(255))
    plant_category = Column(String(255))
    distribution_channel = Column(String(255))
    division = Column(String(255))
    language = Column(String(255))
    is_marked_for_archiving = Column(Boolean, default=False)

class ProductDescription(Base):
    __tablename__ = "product_descriptions"
    product = Column(String(255), primary_key=True)
    language = Column(String(255), primary_key=True)
    product_description = Column(String(255))

class ProductPlant(Base):
    __tablename__ = "product_plants"
    product = Column(String(255), primary_key=True)
    plant = Column(String(255), primary_key=True)
    country_of_origin = Column(String(255))
    region_of_origin = Column(String(255))
    production_invtry_managed_loc = Column(String(255))
    availability_check_type = Column(String(255))
    fiscal_year_variant = Column(String(255))
    profit_center = Column(String(255))
    mrp_type = Column(String(255))

class ProductStorageLocation(Base):
    __tablename__ = "product_storage_locations"
    product = Column(String(255), primary_key=True)
    plant = Column(String(255), primary_key=True)
    storage_location = Column(String(255), primary_key=True)
    physical_inventory_block_ind = Column(String(255))
    date_of_last_posted_cnt_un_rstrcd_stk = Column(Date)

class Product(Base):
    __tablename__ = "products"
    product = Column(String(255), primary_key=True)
    product_type = Column(String(255))
    cross_plant_status = Column(String(255))
    cross_plant_status_validity_date = Column(Date)
    creation_date = Column(Date)
    created_by_user = Column(String(255))
    last_change_date = Column(Date)
    last_change_datetime = Column(TIMESTAMP(timezone=True))
    is_marked_for_deletion = Column(Boolean, default=False)
    product_old_id = Column(String(255))
    gross_weight = Column(Numeric(18, 2))
    weight_unit = Column(String(255))
    net_weight = Column(Numeric(18, 2))
    product_group = Column(String(255))
    base_unit = Column(String(255))
    division = Column(String(255))
    industry_sector = Column(String(255))

class SalesOrderHeader(Base):
    __tablename__ = "sales_order_headers"
    sales_order = Column(String(255), primary_key=True)
    sales_order_type = Column(String(255))
    sales_organization = Column(String(255))
    distribution_channel = Column(String(255))
    organization_division = Column(String(255))
    sales_group = Column(String(255))
    sales_office = Column(String(255))
    sold_to_party = Column(String(255))
    creation_date = Column(Date)
    created_by_user = Column(String(255))
    last_change_datetime = Column(TIMESTAMP(timezone=True))
    total_net_amount = Column(Numeric(18, 4))
    overall_delivery_status = Column(String(255))
    overall_ord_reltd_billg_status = Column(String(255))
    overall_sd_doc_reference_status = Column(String(255))
    transaction_currency = Column(String(255))
    pricing_date = Column(Date)
    requested_delivery_date = Column(Date)
    header_billing_block_reason = Column(String(255))
    delivery_block_reason = Column(String(255))
    incoterms_classification = Column(String(255))
    incoterms_location1 = Column(String(255))
    customer_payment_terms = Column(String(255))
    total_credit_check_status = Column(String(255))

class SalesOrderItem(Base):
    __tablename__ = "sales_order_items"
    sales_order = Column(String(255), primary_key=True)
    sales_order_item = Column(String(255), primary_key=True)
    sales_order_item_category = Column(String(255))
    material = Column(String(255))
    requested_quantity = Column(Numeric(18, 2))
    requested_quantity_unit = Column(String(255))
    transaction_currency = Column(String(255))
    net_amount = Column(Numeric(18, 4))
    material_group = Column(String(255))
    production_plant = Column(String(255))
    storage_location = Column(String(255))
    sales_document_rjcn_reason = Column(String(255))
    item_billing_block_reason = Column(String(255))

class SalesOrderScheduleLine(Base):
    __tablename__ = "sales_order_schedule_lines"
    sales_order = Column(String(255), primary_key=True)
    sales_order_item = Column(String(255), primary_key=True)
    schedule_line = Column(String(255), primary_key=True)
    confirmed_delivery_date = Column(Date)
    order_quantity_unit = Column(String(255))
    confd_order_qty_by_matl_avail_check = Column(Numeric(18, 2))
